### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by KalenAnson** [traildb/traildb#102]
On a fresh install of Debian 8.5 I am unable to get TDB to build properly using either `waf` or autotools.

Here is what I am doing:

    pwd
    ~/Development/traildb
    ./waf configure
    Setting top to                           : /home/username/Development/traildb
    Setting out to                           : /home/username/Development/traildb/build
    Checking for 'gcc' (C compiler)          : /usr/bin/gcc
    Checking for program 'pkg-config'        : /usr/bin/pkg-config
    Checking for 'libarchive'                : yes
    Checking for library Judy                : yes
    Checking Judy version                    : yes

    ./waf build
    {lots of output, looked good to me}

    sudo ./waf install
    Waf: Entering directory `/home/username/Development/traildb/build'
    + install /usr/local/include/traildb.h (from src/traildb.h)
    + install /usr/local/lib/libtraildb.a (from build/libtraildb.a)
    + install /usr/local/include/tdb_error.h (from src/tdb_error.h)
    + install /usr/local/include/tdb_types.h (from src/tdb_types.h)
    + install /usr/local/include/tdb_limits.h (from src/tdb_limits.h)
    + install /usr/local/lib/libtraildb.so.0 (from build/libtraildb.so)
    + symlink /usr/local/lib/libtraildb.so (to libtraildb.so.0)
    + install /usr/local/bin/traildb_bench (from build/traildb_bench)
    + install /usr/local/bin/tdb (from build/tdb)
    + install /usr/local/lib/libtdbindex.so.0 (from build/libtdbindex.so)
    + symlink /usr/local/lib/libtdbindex.so (to libtdbindex.so.0)
    + install /usr/local/share/pkgconfig/traildb.pc (from build/traildb.pc)
    Waf: Leaving directory `/home/username/Development/traildb/build'
    'install' finished successfully (0.141s)

Looks good so far, however running `tdb` gives the following error:

    tdb: error while loading shared libraries: libtraildb.so.0: cannot open shared object file: No such file or directory

Running `ldd` on the tdb binary shows the following problem:

    ldd /usr/local/bin/tdb
        linux-vdso.so.1 (0x00007ffde11f7000)
        libtraildb.so.0 => not found
        libJudy.so.1 => /usr/lib/x86_64-linux-gnu/libJudy.so.1 (0x00007f8e97a93000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8e97876000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8e974cb000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8e97ce5000)

I am also unable to use the ` libtraildb.so.0` file for native bindings (javascript). The `libtraildb.so.0` is present in the following directory: `/usr/local/lib`.

Any idea what I am doing wrong here? Thanks.

**Comment by vladkluev** [comment]
run `ldconfig -v` does libtraildb.so.0 show up?

**Comment by KalenAnson** [comment]
`ldconfig -v` output:

    ...
    /usr/local/lib:
        libtdbindex.so.0 -> libtdbindex.so.0
        libtraildb.so.0 -> libtraildb.so.0
    ...

**Comment by vladkluev** [comment]
Are you on a 32-bit or 64-bit version of debian?

**Comment by KalenAnson** [comment]
64 bit. Not sure what is going on, this is the second fresh system that has not allowed me to build TrailDB properly.

**Comment by rasky** [comment]
Maybe /usr/local/lib isn't on the library path for some reason? ldconfig -p should tell us. You can try reconfiguring with PREFIX=/usr and seeing if that works

**Comment by KalenAnson** [comment]
Ok looks like I needed to manually run `ldconfig` after building and installing the `tdb` binaries and libraries.

I can reproduce the linking problem as follows:

1. Do a `waf uninstall` from the source directory and remove the `build/` directory.
2. Run `ldconfig -v` to rebuild the cache and verify that the cache does not include the `libtraildb.so.0` library files
3. Run `waf configure` then `sudo waf install`
4. At this point the `tdb` binary is not properly linked and shows the error I opened the issue with.
5. Running `ldconfig` now will allow `tdb` cli and libraries to be recognized properly.

Is step 5 normally necessary? I don't remember having to do this on other linux platforms I have build TDB on.

**Comment by KalenAnson** [comment]
Ok I think this is just from the fact that the `ldconfig` cache has not been created on these new systems. I don't think this is necessary a problem with TDB, it was just showing up when I was doing the TDB build on a fresh system.

Thanks for the help guys.
