### ISSUE TITLE
Native Rust Bindings

### ISSUE THREAD

**Issue by syepes** [traildb/traildb#123]
It would be great to see a Native Rust binding

**Comment by syepes** [comment]
https://github.com/JayKickliter/traildb-rs

**Comment by tuulos** [comment]
this is great @syepes ! I believe @knutin was testing this. He may have more comments.

**Comment by knutin** [comment]
Yes, I have a fork of those bindings in a branch at https://github.com/knutin/traildb-rs which is has some bug fixes and support for multi cursors. I'm still polishing, but I think the project is now pretty complete for my use case.

Maybe we could eventually move this under the traildb org?

**Comment by tuulos** [comment]
Yes, we could move it under the Traildb org if the original author(s) are ok with it.

Could you implement the basic example from the tutorial http://traildb.io/docs/tutorial/#part-i-create-a-simple-traildb and include it in `examples/`. I noticed there's a version of the Wikipedia sessions already, which is great.

**Comment by knutin** [comment]
Here's the basic example: https://github.com/knutin/traildb-rs/blob/misc-improvements/examples/simple.rs

I asked the original author his opinion on brining the project under the TrailDB organisation.

**Comment by knutin** [comment]
Original author gave thumbs up. How do we best do this?

**Comment by tuulos** [comment]
I forked  https://github.com/knutin/traildb-rs/ to https://github.com/traildb/traildb-rs. Can we rename this to `traildb-rust` to follow the naming policy for bindings?
