### ISSUE TITLE
Is it possible to get size of not yet finalized DB?

### ISSUE THREAD

**Issue by alexeypetrushin** [traildb/traildb#128]
Something like

```
db = TrailDBConstructor('db', ['username', 'action'])

db.add(uuid, time, (username, action))
...
db.add(uuid, time, (username, action))

print(db.size())
```

Thanks!

**Comment by Noeda** [comment]
I don't think this is possible with the current C API. By size do you mean number of events/trails inserted already to the TrailDB or number of bytes?

I think currently you need to keep track yourself how many events have already been added.

**Comment by alexeypetrushin** [comment]
Number of bytes, amount of memory it consumes. It's hard to do outside of TrailDB because it uses compression so it's not possible to calculate it just as a sum of bytes for every recorded event. 

Anyway, the count of elements should give some estimate...
