### ISSUE TITLE
Cannot use autotools build

### ISSUE THREAD

**Issue by czchen** [traildb/traildb#132]
I use the following command to build traildb with autotools

```
./autogen.sh
./configure
make
```

But have the following errors.

```
tdbcli/tdbcli_tdb-main.o: In function `main':
/home/czchen/src/github.com/traildb/traildb/tdbcli/main.c:307: undefined reference to `op_index'
/home/czchen/src/github.com/traildb/traildb/tdbcli/main.c:309: undefined reference to `op_merge'
tdbcli/tdbcli_tdb-op_dump.o: In function `op_dump':
/home/czchen/src/github.com/traildb/traildb/tdbcli/op_dump.c:226: undefined reference to `apply_filter'
/home/czchen/src/github.com/traildb/traildb/tdbcli/op_dump.c:235: undefined reference to `tdb_index_open'
/home/czchen/src/github.com/traildb/traildb/tdbcli/op_dump.c:236: undefined reference to `tdb_index_match_candidates'
/home/czchen/src/github.com/traildb/traildb/tdbcli/op_dump.c:247: undefined reference to `tdb_index_close'
/home/czchen/src/github.com/traildb/traildb/tdbcli/op_dump.c:232: undefined reference to `tdb_index_find'
```

It looks like autotools build does not update according to the latest code, please help to update it.

**Comment by Noeda** [comment]
I've made changes to the `Makefile.am` which looked like it was missing some source files it was supposed to build (see referenced pull request above). @tuulos

**Comment by tuulos** [comment]
@czchen our official build too is `waf`. Do you think you could use it instead of Autotools? Instructions here https://github.com/traildb/traildb#build-traildb

We can keep Autotools around if necessary but otherwise we would be happy to deprecate it in favor of `waf`.
