### ISSUE TITLE
Q: ha/redundancy/replication

### ISSUE THREAD

**Issue by ivanjaros** [traildb/traildb#140]
Hi,
are there any plans to provide HA setup for cloud environment so TrailDB could be used as central event store for event sourced architecture?

**Comment by tuulos** [comment]
TrailDB by itself is just a library for storing events. It is easy to build cloud-based HA setups on top of it.

For instance, you could have a set of processes consuming events from a Kafka/Kinesis event stream which store batches of events in TrailDBs that are pushed to S3. Another set of readers can read events from TrailDBs in S3 in a very highly available fashion.
