### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by mindis** [traildb/traildb#76]
Hi

I'm trying to build traildb on centos and get following error:

make
/bin/sh ./libtool  --tag=CC   --mode=link gcc -Isrc/ -DJUDYERROR=judyerror_macro_missing_fix_this -O3 -g -Wall    -o tdbcli/tdb tdbcli/tdbcli_tdb-main.o tdbcli/tdbcli_tdb-op_dump.o tdbcli/tdbcli_tdb-op_make.o tdbcli/jsmn/tdbcli_tdb-jsmn.o libtraildb.la -larchive -lJudy
libtool: link: gcc -Isrc/ -DJUDYERROR=judyerror_macro_missing_fix_this -O3 -g -Wall -o tdbcli/.libs/tdb tdbcli/tdbcli_tdb-main.o tdbcli/tdbcli_tdb-op_dump.o tdbcli/tdbcli_tdb-op_make.o tdbcli/jsmn/tdbcli_tdb-jsmn.o  ./.libs/libtraildb.so -larchive -lJudy -Wl,-rpath -Wl,/usr/local/lib
tdbcli/tdbcli_tdb-op_dump.o: In function `tdb_cursor_next':
/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: multiple definition of `tdb_cursor_next'
tdbcli/tdbcli_tdb-main.o:/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: first defined here
tdbcli/tdbcli_tdb-op_make.o: In function `tdb_cursor_next':
/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: multiple definition of `tdb_cursor_next'
tdbcli/tdbcli_tdb-main.o:/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: first defined here
tdbcli/tdbcli_tdb-op_dump.o: In function `op_dump':
op_dump.c:(.text+0xf1): undefined reference to `parse_filter'
collect2: error: ld returned 1 exit status
make: *** [tdbcli/tdb] Error 1

**Comment by rasky** [comment]
Can you try if running `./waf configure build` works for you? 

It looks like the error is caused by a missing `-std=c99` option.

**Comment by mindis** [comment]
still same issue:

./waf configure build

Setting top to                           : /nfs/science/globalscience/mindis/traildb
Setting out to                           : /nfs/science/globalscience/mindis/traildb/build
Checking for 'gcc' (C compiler)          : /usr/bin/gcc
Checking for program 'pkg-config'        : /usr/bin/pkg-config
Checking for 'libarchive'                : yes
Checking for library Judy                : yes
Checking Judy version                    : yes
'configure' finished successfully (1.174s)
Waf: Entering directory `/nfs/science/globalscience/mindis/traildb/build'
Waf: Leaving directory `/nfs/science/globalscience/mindis/traildb/build'
'build' finished successfully (1.168s)

make

/bin/sh ./libtool  --tag=CC   --mode=link gcc -Isrc/ -DJUDYERROR=judyerror_macro_missing_fix_this -O3 -g -Wall    -o tdbcli/tdb tdbcli/tdbcli_tdb-main.o tdbcli/tdbcli_tdb-op_dump.o tdbcli/tdbcli_tdb-op_make.o tdbcli/jsmn/tdbcli_tdb-jsmn.o libtraildb.la -larchive -lJudy
libtool: link: gcc -Isrc/ -DJUDYERROR=judyerror_macro_missing_fix_this -O3 -g -Wall -o tdbcli/.libs/tdb tdbcli/tdbcli_tdb-main.o tdbcli/tdbcli_tdb-op_dump.o tdbcli/tdbcli_tdb-op_make.o tdbcli/jsmn/tdbcli_tdb-jsmn.o  ./.libs/libtraildb.so -larchive -lJudy -Wl,-rpath -Wl,/usr/local/lib
tdbcli/tdbcli_tdb-op_dump.o: In function `tdb_cursor_next':
/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: multiple definition of `tdb_cursor_next'
tdbcli/tdbcli_tdb-main.o:/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: first defined here
tdbcli/tdbcli_tdb-op_make.o: In function `tdb_cursor_next':
/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: multiple definition of `tdb_cursor_next'
tdbcli/tdbcli_tdb-main.o:/nfs/science/globalscience/mindis/traildb/src/traildb.h:220: first defined here
tdbcli/tdbcli_tdb-op_dump.o: In function `op_dump':
op_dump.c:(.text+0xf1): undefined reference to `parse_filter'
collect2: error: ld returned 1 exit status
make: *** [tdbcli/tdb] Error 1

**Comment by rasky** [comment]
waf builds the library, you don't need make afterwards, and it looks like it worked. Try also "./waf clean" if you want to try from scratch.

Look into the build directory, you should find the binaries there.

**Comment by mindis** [comment]
thanks, great it worked!
