### ISSUE TITLE
Incorrect filter logic if you leave a trailing "new clause"

### ISSUE THREAD

**Issue by JoshVorick** [traildb/traildb#80]
Say I want to add a list of items to a filter connected by AND clauses using this logic:

```
filter = tdb_event_filter_new();
for item in items {
    tdb_event_filter_add_term(filter, item, 0);
    tdb_event_filter_new_clause(filter);
}
```

The filter always returns false in `event_satisfies_filter()`.

Using the following logic, however, works:

```
filter = tdb_event_filter_new();
for item in items {
    tdb_event_filter_add_term(filter, item, 0);
    if (item != items[len - 1]) // not the last item
        tdb_event_filter_new_clause(filter);
}
```

Is this a design decision? Personally I think it would be easier to create filters if hanging empty clauses were allowed. Maybe I'm just going about filters wrong?

**Comment by tuulos** [comment]
Filters are expressed in Conjunctive Normal Form, i.e. `(a OR b OR c) AND (d OR e)`.

`tdb_event_filter_new_clause()` adds an AND in the sequence. In your first example, the filter ends up being `(item1) AND (item2) AND ... (itemK) AND ()`. The last clause is empty so the whole sequence of clauses matches nothing.

In the second example, you get `(item1) AND (item2) ... AND (itemK)`, so it can match some events.

Empty clauses are allowed and they behave as empty sets should. I can see how it can be a bit confusing but I am not sure what would be a better alternative.

**Comment by JoshVorick** [comment]
Okay, thanks for explaining that! Makes a lot of sense :)
